server:
  port: 1117
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/db_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10

